"""
LEIP backend — MVP demo API.

Serves ambulance, hospital, doctor, and dashboard-statistics data over REST,
and streams live ambulance movement/vitals over a WebSocket. No real medical
devices are connected; the live feed is generated by `simulation.py`.

Every tick's result — and every dispatch/arrival/notification event — is
persisted to the database (SQLite by default, Postgres via DATABASE_URL), so
the fleet, activity log, and notifications all survive a backend restart.

Run:
    pip install -r requirements.txt
    uvicorn main:app --reload
"""
import asyncio
import json
from datetime import datetime

from fastapi import FastAPI, WebSocket, WebSocketDisconnect, Depends
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session

import simulation as sim
import models_db as models
from database import engine, SessionLocal, get_db
from auth import hash_password
from routers import auth as auth_router
from routers import patients as patients_router
from routers import reports as reports_router

models.Base.metadata.create_all(bind=engine)

app = FastAPI(title="LEIP — Emergency Intelligence Platform API", version="0.1.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # tighten to the deployed frontend origin in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(auth_router.router)
app.include_router(patients_router.router)
app.include_router(reports_router.router)

# Module-level default so `main.fleet` always resolves (routers/reports.py
# imports it lazily); `startup_hydrate_fleet` below replaces it with either
# the persisted state from the database or a freshly seeded one.
fleet = sim.Fleet()

DEMO_USERS = [
    {"name": "Sanya Kapoor", "email": "ems@leip.demo", "password": "demo1234", "role": "ems_command"},
    {"name": "Rakesh Sharma", "email": "staff@leip.demo", "password": "demo1234", "role": "ambulance_staff"},
    {"name": "Dr. Ananya Iyengar", "email": "doctor@leip.demo", "password": "demo1234", "role": "doctor", "hospital": "St. Xavier General"},
    {"name": "Kavya Rao", "email": "family@leip.demo", "password": "demo1234", "role": "family"},
]


def _ambulance_row_to_dict(row: models.AmbulanceRecord) -> dict:
    return {
        "id": row.id, "driver": row.driver, "driver_phone": row.driver_phone, "status": row.status,
        "lat": row.lat, "lng": row.lng, "speed": row.speed,
        "eta_minutes": row.eta_minutes, "hospital": row.hospital,
        "patient_name": row.patient_name, "patient_age": row.patient_age,
        "patient_gender": row.patient_gender, "patient_blood_group": row.patient_blood_group,
        "patient_history": row.patient_history, "patient_allergies": row.patient_allergies,
        "heart_rate": row.heart_rate, "bp_systolic": row.bp_systolic, "bp_diastolic": row.bp_diastolic,
        "spo2": row.spo2, "temperature": row.temperature, "respiratory_rate": row.respiratory_rate,
    }


def persist_fleet_snapshot(db: Session):
    for row in fleet.snapshot_rows():
        db.merge(models.AmbulanceRecord(**row))
    db.commit()


def log_event(db: Session, text: str, ambulance_id: str | None = None):
    db.add(models.EventRecord(ambulance_id=ambulance_id, text=text))
    db.commit()


@app.on_event("startup")
def startup_seed_and_hydrate():
    """Runs once at boot: seeds demo users/hospitals/doctors on first run,
    and resumes the ambulance fleet from the database if it was persisted
    by a previous run — otherwise seeds a fresh fleet and saves it."""
    global fleet
    db = SessionLocal()
    try:
        for u in DEMO_USERS:
            if not db.query(models.User).filter(models.User.email == u["email"]).first():
                db.add(models.User(
                    name=u["name"], email=u["email"], role=u["role"],
                    hashed_password=hash_password(u["password"]), hospital=u.get("hospital"),
                ))

        if not db.query(models.HospitalRecord).first():
            for h in sim.HOSPITALS:
                db.add(models.HospitalRecord(name=h["name"], lat=h["lat"], lng=h["lng"], load=h["load"]))

        if not db.query(models.DoctorRecord).first():
            for d in sim.DOCTORS:
                db.add(models.DoctorRecord(name=d["name"], specialty=d["specialty"], hospital=d["hospital"]))

        db.commit()

        rows = db.query(models.AmbulanceRecord).all()
        if rows:
            fleet = sim.Fleet(seed_rows=[_ambulance_row_to_dict(r) for r in rows])
            print(f"Resumed fleet from database ({len(rows)} units).")
        else:
            fleet = sim.Fleet()
            persist_fleet_snapshot(db)
            log_event(db, "Command center initialized — fleet seeded")
            print("Seeded a fresh fleet into the database.")
    finally:
        db.close()

    print("Demo logins ready — password 'demo1234' for: " + ", ".join(u["email"] for u in DEMO_USERS))


@app.get("/")
def root():
    return {"service": "LEIP API", "status": "ok", "time": datetime.now().isoformat()}


@app.get("/api/ambulances")
def get_ambulances():
    return fleet.to_dict()


@app.get("/api/ambulances/nearby")
def get_nearby_ambulances(lat: float, lng: float, limit: int = 5):
    """Nearest currently-available ambulances to a given point, each with the
    driver's phone number — used by the Family dashboard's ambulance finder."""
    return fleet.nearest_available(lat, lng, limit)


@app.get("/api/ambulances/{ambulance_id}")
def get_ambulance(ambulance_id: str):
    for a in fleet.ambulances:
        if a.id == ambulance_id:
            data = a.to_dict()
            data["ai_summary"] = sim.ai_summary(a)
            data["family_message"] = sim.family_message(a)
            return data
    return {"error": "not found"}, 404


@app.get("/api/stats")
def get_stats():
    return fleet.stats()


@app.get("/api/hospitals")
def get_hospitals(db: Session = Depends(get_db)):
    rows = db.query(models.HospitalRecord).all()
    return [{"name": r.name, "lat": r.lat, "lng": r.lng, "load": r.load} for r in rows]


@app.get("/api/doctors")
def get_doctors(db: Session = Depends(get_db)):
    rows = db.query(models.DoctorRecord).all()
    return [{"name": r.name, "specialty": r.specialty, "hospital": r.hospital} for r in rows]


@app.get("/api/events")
def get_events(db: Session = Depends(get_db), limit: int = 30):
    rows = (
        db.query(models.EventRecord)
        .order_by(models.EventRecord.created_at.desc())
        .limit(limit)
        .all()
    )
    return [
        {"id": r.id, "ambulance_id": r.ambulance_id, "text": r.text, "time": r.created_at.strftime("%H:%M:%S")}
        for r in rows
    ]


@app.get("/api/notifications")
def get_notifications(db: Session = Depends(get_db), limit: int = 30):
    rows = (
        db.query(models.NotificationRecord)
        .order_by(models.NotificationRecord.created_at.desc())
        .limit(limit)
        .all()
    )
    return [
        {"id": r.id, "ambulance_id": r.ambulance_id, "hospital": r.hospital, "message": r.message,
         "time": r.created_at.strftime("%H:%M:%S")}
        for r in rows
    ]


@app.get("/api/ambulances/{ambulance_id}/ai-summary")
def get_ai_summary(ambulance_id: str):
    for a in fleet.ambulances:
        if a.id == ambulance_id:
            return {"ambulance_id": ambulance_id, "summary": sim.ai_summary(a)}
    return {"error": "not found"}, 404


@app.get("/api/family/{ambulance_id}")
def get_family_view(ambulance_id: str):
    """Everything the Family dashboard needs in one call: condition, ETA,
    hospital, live location, and a plain-language message."""
    for a in fleet.ambulances:
        if a.id == ambulance_id:
            timeline = ["Ambulance dispatched", "Patient picked up", "Doctor reviewing", "Hospital informed"]
            if a.status == "arrived":
                timeline.append("Arrived at hospital")
            elif a.eta_minutes is not None:
                timeline.append(f"Arriving in {a.eta_minutes} minutes")
            return {
                "ambulance_id": a.id,
                "patient_name": a.patient.name if a.patient else None,
                "condition": "Critical — being closely monitored" if a.status == "critical" else "Stable",
                "eta_minutes": a.eta_minutes,
                "hospital": a.hospital,
                "lat": a.lat,
                "lng": a.lng,
                "status": a.status,
                "message": sim.family_message(a),
                "timeline": timeline,
            }
    return {"error": "not found"}, 404


@app.post("/api/ambulances/{ambulance_id}/notify-hospital")
def notify_hospital(ambulance_id: str, db: Session = Depends(get_db)):
    for a in fleet.ambulances:
        if a.id == ambulance_id:
            message = f"{a.hospital} notified — ETA {a.eta_minutes or '—'} min, status {a.status}."
            db.add(models.NotificationRecord(ambulance_id=a.id, hospital=a.hospital, message=message))
            log_event(db, f"{a.id} — hospital notified ({a.hospital})", ambulance_id=a.id)
            return {"ok": True, "message": message}
    return {"error": "not found"}, 404


@app.post("/api/ambulances/{ambulance_id}/send-to-hospital")
def send_to_hospital(ambulance_id: str, db: Session = Depends(get_db)):
    for a in fleet.ambulances:
        if a.id == ambulance_id:
            if a.status == "available":
                return {"error": "Unit has no active patient to transport"}, 400
            a.status = "responding" if a.status != "critical" else "critical"
            persist_fleet_snapshot(db)
            log_event(db, f"{a.id} sent to {a.hospital}", ambulance_id=a.id)
            return {"ok": True, "status": a.status, "hospital": a.hospital}
    return {"error": "not found"}, 404


@app.websocket("/ws/ambulances")
async def ws_ambulances(websocket: WebSocket):
    """
    Streams the full fleet state every 2 seconds (matching the "GPS updates
    every two seconds" requirement) plus discrete event notifications
    whenever a dispatch, arrival, or critical alert occurs. Every tick's
    result and every event is also persisted to the database.
    """
    await websocket.accept()
    try:
        await websocket.send_text(json.dumps({"type": "ambulances", "data": fleet.to_dict()}))
        while True:
            await asyncio.sleep(2)
            events = fleet.tick()
            db = SessionLocal()
            try:
                persist_fleet_snapshot(db)
                for text in events:
                    ambulance_id = text.split(" ", 1)[0]
                    log_event(db, text, ambulance_id=ambulance_id)
            finally:
                db.close()
            await websocket.send_text(json.dumps({"type": "ambulances", "data": fleet.to_dict()}))
            for text in events:
                await websocket.send_text(json.dumps({"type": "event", "text": text}))
    except WebSocketDisconnect:
        pass
